/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bedding-store/public/models/bed.glb -o temp.js
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/bed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={3} decay={2} rotation={[-1.326, -1.18, -1.307]} target={nodes.Key_Light.target}>
        <primitive object={nodes.Key_Light.target} position={[0, 0, -1]} />
      </directionalLight>
      <mesh geometry={nodes.GlamVelvetSofa_legs.geometry} material={materials.GlamVelvetSofa_legs} />
      <mesh geometry={nodes.GlamVelvetSofa_fabric.geometry} material={materials.GlamVelvetSofa_fabric_navy} />
      <mesh geometry={nodes.GlamVelvetSofa_feet.geometry} material={materials.GlamVelvetSofa_feet} />
    </group>
  )
}

useGLTF.preload('/bed.glb')
